### ISSUE TITLE
how to publish public scoped package ?

### ISSUE THREAD

**Issue by kopax** [bahmutov/ci-publish#10]
Hi,
I would like to publish a public scoped package (https://www.npmjs.com/docs/orgs/publishing-an-org-scoped-package.html#publishing-a-public-scoped-package)

My CI is failing with : 

```bash
npm ERR! publish Failed PUT 402
npm ERR! code E402
npm ERR! You must sign up for private packages : 
```

**Comment by baoduy** [comment]
I'm also facing the same issue. Suggest allow passing the --access publish to npm publish command.
