### ISSUE TITLE
Encrypt the auth token

### ISSUE THREAD

**Issue by RobLoach** [bahmutov/ci-publish#3]
If other's get hold of the auth token, they could make releases as yourself.

https://docs.travis-ci.com/user/encryption-keys/

**Comment by hutson** [comment]
@RobLoach using encrypted keys is unnecessary for Travis CI in general. The only time you need to encrypt an environment variable is when using a different value per branch (Please see _Environment Variables_ documentation on Travis CI - https://docs.travis-ci.com/user/environment-variables)

**Comment by RobLoach** [comment]
Cool!
