### ISSUE TITLE
I Need Some Advice

### ISSUE THREAD

**Issue by hutson** [bahmutov/ci-publish#5]
Howdy @bahmutov,

I'm looking at [refactoring semantic-release-gitlab](https://gitlab.com/hyper-expanse/semantic-release-gitlab/issues/13) to remove package publishing from `semantic-release-gitlab`, and move that functionality into a separate package.

The act of publishing an npm package to the npm registry would fall into a job separate from the job that publishes a tag and release notes to GitLab.

A detailed explanation of the goal, and reasoning, is available at the link above.

It looks like `ci-publish` can handle most of my requirements, such as setting up the CI's `.npmrc` configuration file, and calling `npm publish`.

The one remaining requirement, because of the way `semantic-release-gitlab` generates a new version based on the commits since the last tag, is the need to write a version number to the `package.json`. 

If publishing to the npm registry happens in a separate job from the job that runs `semantic-release-gitlab`, the value written to `package.json` by `semantic-release-gitlab` won't be available during the npm publish.

Therefore, I was wondering whether I should bake `ci-publish` into another tool that also [writes the version number to a package.json file](https://gitlab.com/hyper-expanse/semantic-release-gitlab/blob/master/src/bump.js#L30), or whether that functionality can, or should, exist in a project like `ci-publish`?

**Comment by bahmutov** [comment]
I like the way you are thinking! I think updating the `package.json` version is pretty small command, and we could make it part of `ci-publish`. I will make you a collaborator in this - feel free to hack away on the master, ok?

**Comment by hutson** [comment]
That sounds great @bahmutov.

To get the version, I would need to fetch it from `git tags`. Is it safe to assume that all CI systems where this would be used have `git` in the build user's path, and have the to-be-built project's `.git` directory (git metadata) available as well?

**Comment by bahmutov** [comment]
That's a good question, I think we cannot assume that. I think we need to run `git pull --tag` command to get the tags.

**Comment by hutson** [comment]
I couldn't find a `--tag` option for `git pull` - https://git-scm.com/docs/git-pull#git-pull---no-tags

**Comment by bahmutov** [comment]
Hmm, I guess it is the opposite, and the tags are fetched automatically unless there is `--no-tags` option. This is so weird, I remember just writing this in https://github.com/bahmutov/ggit/commit/106bfd71a4f4dd6b119a89ab0648759d812b3026 What is going here ;)

**Comment by bahmutov** [comment]
It makes sense that you cannot fetch just the tags (what would they refer to without objects?)

**Comment by hutson** [comment]
So my idea:

```javascript
#!/usr/bin/env node

// https://www.npmjs.com/package/ggit
var tags = require('ggit').tags
// https://www.npmjs.com/package/modify-pkg-up
var modifyPkg = require('modify-pkg-up')
var npm = require('npm-utils')

function onError (err) {
  console.error(err)
  process.exit(-1)
}

tags
  .then(tags => tags[tags.length-1])
  .then((version => modifyPkg(pkg => Object.assign(pkg, { version: version })))
  .then(npm.setAuthToken())
  .then(npm.publish)
  .catch(onError)
```

Downsides
* Two new direct dependencies, and several new transitive dependencies.
* Restricts `ci-publish` to Git (Not other SCM tools supported).
* Restricts `ci-publish` to CI platforms that setup the build environment with a cloned copy of the project (One that includes a `.git` directory, instead of extracting a tarball of the project into the build directory)
* Restricts Node support to Node 4 and higher. (Because of arrow functions and `Object.assign`)
* Assumes tag is valid by `node-semver`.

**Comment by hutson** [comment]
I ended up creating a package called [npm-publish-git-tag](https://www.npmjs.com/package/npm-publish-git-tag).

After detailing the downsides of my approach, it didn't seem appropriate to take what's already a great package and limit the scope of its functionality to workflows that use `git`, and CI platforms that expose `git`.

Therefore I'm leaving `ci-publish` to continue supporting its users, while providing a publishing tool for those that use tools like `semantic-release-gitlab`.

**Comment by bahmutov** [comment]
Perfect decision, agree with your logic @hbetts
