### ISSUE TITLE
how to publish to custom registry

### ISSUE THREAD

**Issue by smoebody** [bahmutov/ci-publish#7]
With `npm publish` one publishes to the authenticated registry. With `npm run ci-publish` one publishes to the default registry with the token provided in `NPM_TOKEN`.

How do you suggest to provide the custom registry for publishing? I tried providing the option `--registry http ...` as well as the environment variable `npm_config_registry=http ...` without success.

thanks for your help

**Comment by bahmutov** [comment]
Can you set the registry in npmrc file or package.json file?

**Comment by smoebody** [comment]
Well, setting up the .npmrc requires additional steps which supersedes the benefits of ci-publish for me - simple publish.
Specifying the registry in package.json i haven't done before. I need to figure out, whether i want this in my project. I come back to you as soon as i have the information.
Thanks so far.

**Comment by bahmutov** [comment]
Otherwise you can trace argument flow into ci publish and if and how you can add registry argument.

**Comment by ghost** [comment]
@smoebody `ci-publish` uses `npm-utils` as its core library, and `npm-utils` supports the `publishConfig` property in `package.json`.

Here's the reference to the pull request I filed that added that support - https://github.com/bahmutov/npm-utils/pull/48

The pull request description contains a few more details.
